spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/aji-n9raw-kitab
    username: username
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: localhost
    port: 1025
    username: abde
    password: abde
    properties:
      mail:
        smtp:
          trust: "*"
        auth: true
        starttls:
          enable: true
        connectiontimout: 5000
        timeout: 3000
        writetimeout: 5000

application:
  security:
    jwt:
        secret-key: 19536fbe235695457f4671bdf8ffd13cd889852ce92563f48a2cabe1ef3f992e98a6ca1e7d0c50d2a8fb0216d4af2dc02eec29ebefdb6ed4c4b0637fdf61b938c79969b94cbe1839f2505d671d48d606fe5a57960b1148dd37f9470a199189ec03a19c906bfc8646934c25fac2cfb4631675b4d57f7b71b1b402cd5b8dfd8cad048f11fb3be14fcd1d5fbfd3d7624b3c3ef75742221667ca318d3abb6699aa87a6875cf8f6259b7d3efedd873cbbc6f0e1b32d7698f574ab56d5d374514b6eb93d0344ab6ade2abd32a5be41f418aad2be211bdcc23f5ded3a4ec1f82034ac48a015818a463fe42e54c8c0ff7a4c3e3397ca21b2ef83c3873a2c9acd521eb404
        expiration: 8640000
  mailing:
    frontend:
      activationUrl: http://localhost:4200/activate-account
  photos:
    output:
      path: ./uploads
server:
  port: 8088
