spring:
  profiles:
    active: dev
  servlet:
    #This configures settings for handling file uploads in the application.
    multipart:
      max-file-size: 50MB
#This section configures settings related to SpringDoc, which is used to generate API documentation (usually OpenAPI or Swagger)
springdoc:
  #This specifies the default media type that the API will produce in its responses.
  default-produces-media-type: application/json

server:
  servlet:
    context-path: /api/v1/