services:
  postgres:
    container_name: postgres-sql-ank
    image: postgres
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: aji-n9raw-kitab
    volumes:
      - postgres:/data/postgres
    ports:
      - 5432:5432
    networks:
      - spring-demo
    restart: Unless-stopped
  mail-dev:
    container_name: mail-dev-ank
    image: maildev/maildev
    ports:
      - 1080:1080 //to display the ui of the app
      - 1025:1025 //used for us to implement the mailing


networks:
  -spring-demo:
    driver: bridge

volumes:
  postgres:
    driver: local